### PR TITLE
Update Org Name & Links in README

### PR DESCRIPTION
**Pull request by zicklag**
s/fishfight/fishfolks/

### CODE REVIEW

**Review by erlend-sh — APPROVED** [review]

**Review by erlend-sh — CHANGES_REQUESTED** [review]
Also change top header.

**Comment by zicklag** [comment]
bors cancel

**Comment by zicklag** [comment]
Searched the whole repo and replaced occurrences throughout.

**Review by erlend-sh — APPROVED** [review]

**Pull request merged**
