### PR TITLE
Rebase Boss MVP by @edgarssilva

### PR DESCRIPTION
**Pull request by zicklag**
Rebases #200 onto the latest master, with a couple subjective tweaks:

- Make boss flag in YAML a `bool` instead of an `Option<bool>`
- Impl HasLoadProgress for `bool` instead of ignoring the `boss` field
  in the metata struct.

Otherwise this is pretty much all just @edgarssilva's code.

@edgarssilva , you can push to this branch to do anything else you want to do with this before merging, if anything.

### CODE REVIEW

**Review by edgarssilva — APPROVED** [review]
Seems great thanks for the help.
Also, the attack logic isn't great and can lead to odd behavior but I didn't worry too much since we are changing it later.

**Comment by odecay** [comment]
I think we are supposed to be using bors to merge stuff now, and remember to make the formatting checks pass also

**Comment by edgarssilva** [comment]
> I think we are supposed to be using bors to merge stuff now, and remember to make the formatting checks pass also

Ho your right sorry, totally went over my head.

**Comment by zicklag** [comment]
You can require bors to pass before merging on the branch protection rules, which would prevent this from accidentally happening in the future. I've almost clicked it a couple of times before remembering I was supposed to tell bors to merge it:

image

**Comment by edgarssilva** [comment]
> You can require bors to pass before merging on the branch protection rules, which would prevent this from accidentally happening in the future. I've almost clicked it a couple of times before remembering I was supposed to tell bors to merge it:

Done, also should I enable "Require a pull request before merging" so that also doesn't happen accidentally.

**Pull request merged**
